export const data = [
    {
      nomor: 1,
      auditan:'ir2',
      nomorSurat: '123/XYZ/2024',
      stTanggalMulai: '2024-07-01',
      stTanggalSelesai: '2024-07-05',
      tanggalSuratPemberitahuan: '2024-06-20',
      jumlahHariPemberitahuan: 10,
      kesesuaianPemberitahuan: true,
      skorPemberitahuan: 5,
      jumlahHariAudit: 5,
      kesesuaianAudit: true,
      skorAudit: 4,
      inspekturHadir: true,
      jumlahOrang: 3,
      kesesuaianSDM: true,
      skorSDM: 5,
      tanggalTindakLanjut: '2024-07-08',
      tanggalVerifikasi: '2024-07-15',
      kesesuaianTindakLanjut: true,
      skorTindakLanjut: 4,
      tanggalBAExit: '2024-07-05',
      tanggalTerbitIHA: '2024-07-10',
      tanggalTerbitLHA: '2024-07-15',
      kesesuaianIHA: true,
      skorIHA: 5,
      tanggalSelesaiTL: '2024-07-30',
      tanggalSelesaiAudit: '2024-08-05',
      kesesuaianAuditSelesai: true,
      skorAuditSelesai: 5,
      persentaseKesesuaian: 90,
      kategori: "domestik",
    },
    {
      nomor: 2,
      auditan:'ir4',
      nomorSurat: '456/ABC/2024',
      stTanggalMulai: '2024-08-01',
      stTanggalSelesai: '2024-08-05',
      tanggalSuratPemberitahuan: '2024-07-20',
      jumlahHariPemberitahuan: 10,
      kesesuaianPemberitahuan: true,
      skorPemberitahuan: 5,
      jumlahHariAudit: 5,
      kesesuaianAudit: true,
      skorAudit: 4,
      inspekturHadir: true,
      jumlahOrang: 3,
      kesesuaianSDM: true,
      skorSDM: 5,
      tanggalTindakLanjut: '2024-08-08',
      tanggalVerifikasi: '2024-08-15',
      kesesuaianTindakLanjut: true,
      skorTindakLanjut: 4,
      tanggalBAExit: '2024-08-05',
      tanggalTerbitIHA: '2024-08-10',
      tanggalTerbitLHA: '2024-08-15',
      kesesuaianIHA: true,
      skorIHA: 5,
      tanggalSelesaiTL: '2024-08-30',
      tanggalSelesaiAudit: '2024-09-05',
      kesesuaianAuditSelesai: true,
      skorAuditSelesai: 5,
      persentaseKesesuaian: 90,
      kategori: "luar negeri",
    },
    // Tambahkan data lainnya sesuai kebutuhan
  ];

